### ISSUE TITLE
Got Http response code 401 when accessing https://api.sandbox.paypal.com/v1/oauth2/token. Retried 0 times

### ISSUE THREAD

**Issue by LeventeNagy** [xroot/laravel-paypalpayment#11]
Copied the example code to test, client id and secret are fine but i get this error

Got Http response code 401 when accessing https://api.sandbox.paypal.com/v1/oauth2/token. Retried 0 times

**Comment by dcolumbus** [comment]
@xroot my credentials are correct, yes.

**Comment by LeventeNagy** [comment]
Hi guys, i solved the problem in one of my older projects, let me dig it out and i will post the fix

**Comment by xroot** [comment]
run composer update. then make sure yr ApiContext looks something like this Paypalpayment::ApiContext($this->_ClientId, $this->_ClientSecret); you only need to pass clientID and ClienSecret .

**Comment by josephilipraja** [comment]
FIXED! My constructor had: 
```
$this->_apiContext = Paypalpayment::ApiContext(
    Paypalpayment::OAuthTokenCredential(
        $this->_ClientId,
        $this->_ClientSecret
    ), 'Request' . time()
);
```
I changed to 
```
$this->_apiContext = Paypalpayment::ApiContext($this->_ClientId, $this->_ClientSecret);
```
and it worked just like that!

> I was mislead by the old README docs. @xroot changed it recently with this commit - https://github.com/xroot/laravel-paypalpayment/commit/89a0c1b3bc061c82a7d4c37fca7db91da0201169

**Comment by ChristianGB** [comment]
Thnks man I'll check my page and how it will change

2015-04-21 4:31 GMT-05:00 Jose Philip Raja <notifications@github.com>:

> FIXED! My constructor had:
>
> $this->_apiContext = Paypalpayment::ApiContext(
>     Paypalpayment::OAuthTokenCredential(
>         $this->_ClientId,
>         $this->_ClientSecret
>     ), 'Request' . time()
> );
>
> I changed to
>
> $this->_apiContext = Paypalpayment::ApiContext($this->_ClientId, $this->_ClientSecret);
>
> and it worked just like that!
>
> I was mislead by the old README docs. @xroot <https://github.com/xroot>
> changed it recently with this commit - 89a0c1b
> <https://github.com/xroot/laravel-paypalpayment/commit/89a0c1b3bc061c82a7d4c37fca7db91da0201169>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xroot/laravel-paypalpayment/issues/11#issuecomment-94720469>
> .
>



-- 

*Christian Eduardo Galdámez Blanco*

*Ingeniero en Desarrollo de Software*

*Facebook: https://www.facebook.com/shiroiMangetsu
<https://www.facebook.com/shiroiMangetsu>Teléfono: 044 961 270 47 69*

**Comment by sharjeeldevep** [comment]
Hey Guys,

I was facing same issue then got solution.

change mode "sandbox" to "live" and  log.LogLeve "DEBUG" to "LIVE"
/* Sandbox * /
    $apiContext->setConfig(
        array(
            'mode' => 'sandbox',
            'log.LogEnabled' => true,
            'log.FileName' => '../PayPal.log',
            'log.LogLevel' => 'DEBUG', // PLEASE USE `FINE` LEVEL FOR LOGGING IN LIVE ENVIRONMENTS
            'cache.enabled' => true,
            // 'http.CURLOPT_CONNECTTIMEOUT' => 30
            // 'http.headers.PayPal-Partner-Attribution-Id' => '123123123'
        )
    );
    /* */
    /* For Live */
    $apiContext->setConfig(
        array(
            'mode' => 'live',
            'log.LogEnabled' => true,
            'log.FileName' => '../PayPal.log',
            'log.LogLevel' => 'FINE', // PLEASE USE `FINE` LEVEL FOR LOGGING IN LIVE ENVIRONMENTS
            'cache.enabled' => true,
            // 'http.CURLOPT_CONNECTTIMEOUT' => 30
            // 'http.headers.PayPal-Partner-Attribution-Id' => '123123123'
        )
    );
    /* */

**Comment by avinashpothula** [comment]
Response code: 415	Error response: Server returned HTTP response code: 415 for URL: https://api.sandbox.paypal.com/v1/oauth2/token
what was that meaning my credentials are correct . how to solve this error 
any one help in java

**Comment by kamleshwebtech** [comment]
I got the solution, Just added paypal client_id, secret and paypal mode (sandbox or live) in dot env file then re-run php artisan serve command in command line. I was 100% sure, it will work. I did it and it worked, very happy now. thank for asking this question.
