### ISSUE TITLE
using paypal method

### ISSUE THREAD

**Issue by lucabro81** [xroot/laravel-paypalpayment#14]
Sorry i've some trouble to post the issue. However using paypal method I've modified the create controller in this way:

```
public function create()
{
        $payer = Paypalpayment::Payer();
        $payer->setPayment_method("paypal");

        $amount = Paypalpayment:: Amount();
        $amount->setCurrency("USD");
        $amount->setTotal("1.00");

        $transaction = Paypalpayment:: Transaction();
        $transaction->setAmount($amount);
        $transaction->setDescription("This is the payment description.");

        $paymentId = '1234';
        $PayerID = 'payerID@yahoo.it';

        $payment = Paypalpayment:: Payment();
        $payment->setIntent("sale");
        $payment->setPayer($payer);
        $payment->setTransactions(array($transaction));

        $payment->get($paymentId, $this->_apiContext);
    $execution = Paypalpayment::PaymentExecution();
        $execution->setPayer_id($PayerID);

        //Execute the payment
       $payment->execute($execution,$this->_apiContext);
}
```

And this is the error:

PayPal \ Exception \ PPConnectionException

Got Http response code 404 when accessing https://api.sandbox.paypal.com/v1/payments/payment/1234. Retried 0 times.

PaymentId is 1234 only for test, what is the problem? The $_ClientId and $_ClientSecret are correctly setted.

And another question, how can i redirect to my site after payment?

Thankyou very much

**Comment by baljeetbhinder** [comment]
Hi @xroot ,
Can you please help me out.
I have followed your instructions in the comments above and created those 3 methods:
public function create()
public function getConfirmpayment()
public function getCancelpayment()
just the way you did.
When I hit http://localhost:8000/payment/create
it takes me the paypal website correctly as expected.
 then I log in with my sandbox details.
It gets me to the "Review your information" page.(PFA)
and just after I click Continue:
 Here the problem Occurs:(PFA)
PayPalConnectionException in PayPalHttpConnection.php line 176: Got Http response code 404 when accessing https://api.sandbox.paypal.com/v1/payments/payment/confirmpayment.

![1 working fine -review your information](https://cloud.githubusercontent.com/assets/8347607/8843751/74a923ea-312a-11e5-91de-6da17deb2c66.png)
![2 error screen](https://cloud.githubusercontent.com/assets/8347607/8843752/74adad02-312a-11e5-9dac-855991372438.png)

Can you help me out please?
Thanks
