### ISSUE TITLE
live mode not working 

### ISSUE THREAD

**Issue by abhitheawesomecoder** [xroot/laravel-paypalpayment#25]
Even when i am setting mode to live like below its redirecting to https://www.sandbox.paypal.com

$this->_apiContext->setConfig(array(
            'mode' => 'live',
            'http.ConnectionTimeOut' => 30,
            'log.LogEnabled' => true,
            'log.FileName' => __DIR__.'/../PayPal.log',
            'log.LogLevel' => 'FINE'
        ));

how to make it redirect to https://www.paypal.com and not https://www.sandbox.paypal.com?

**Comment by xroot** [comment]
does your issue resolved ?

**Comment by rifayman** [comment]
for me even if i had  changed sdk_config.ini  it does not work
