### ISSUE TITLE
Error directly after install. 

### ISSUE THREAD

**Issue by justgage** [xroot/laravel-paypalpayment#3]
when I try to run any command or access any page I get this:
![screen shot 2013-10-22 at 3 03 07 pm](https://f.cloud.github.com/assets/164033/1385364/7131517a-3b5d-11e3-971b-aac47691d911.png)
console error: 
HP Fatal error:  Call to undefined method Anouar\Paypalpayment\Facades\PaypalPayment::isDeferred() in /Users/gages/laravel/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 94

``` json
{{
   "error":{
      "type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException",
      "message":"Call to undefined method Anouar\\Paypalpayment\\Facades\\PaypalPayment::isDeferred()",
      "file":"\/Users\/joeolivas\/Desktop\/gages\/butterfly-laravel\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/ProviderRepository.php",
      "line":94
   }
}
```

I have tried with and without a controller file, same error, breaking laravel as an entirety.

**Comment by imdketav** [comment]
@xroot  I followed all steps as you mention but when I run script it will through an error like this.
FatalErrorException in PaypalPaymentController.php line 41:
Class 'Paypalpayment' not found
![screenshot from 2015-10-08 18 33 58](https://cloud.githubusercontent.com/assets/15032918/10366947/2d479df8-6deb-11e5-910a-d4c27826db66.png)

**Comment by chilion** [comment]
Seems like you didn't add a USE in the top of your code? Can you show your code?

**Comment by imdketav** [comment]
@chilion  This is my code

<?php

namespace my_app\Http\Controllers;

use Illuminate\Http\Request;
use my_app\Http\Requests;
use my_app\Http\Controllers\Controller;
use Paypalpayment;

class PaypalPaymentController extends Controller {
    /**
     * object to authenticate the call.
     * @param object $_apiContext
     */
    private $_apiContext;

    /**
     * Set the ClientId and the ClientSecret.
     * @param 
     *string $_ClientId
     *string $_ClientSecret
     */
    private $_ClientId='AZt_MjouRUFKuN9UGRTZfG2NnN6c5qeRDPk4XLvv2RpgTUXZZhWHYLPX6sEazQL-kbiRU5116czfZF72';
    private $_ClientSecret='ECzJoFchZijyj7V660ua99-GB9NshQJ1oJcMhlXHM7WDWibnjWK7S6c1ujAXYYmIW-F864goSFwffKjV';

    /*
     *   These construct set the SDK configuration dynamiclly, 
     *   If you want to pick your configuration from the sdk_config.ini file
     *   make sure to update you configuration there then grape the credentials using this code :
     *   $this->_cred= Paypalpayment::OAuthTokenCredential();
    */
    public function __construct(){

        // ### Api Context
        // Pass in a `ApiContext` object to authenticate 
        // the call. You can also send a unique request id 
        // (that ensures idempotency). The SDK generates
        // a request id if you do not pass one explicitly. 


        $this->_apiContext = Paypalpayment:: ApiContext(
                Paypalpayment::OAuthTokenCredential(
                    $this->_ClientId,
                    $this->_ClientSecret
                )
        );

        // dynamic configuration instead of using sdk_config.ini

        $this->_apiContext->setConfig(array(
            'mode' => 'sandbox',
            'http.ConnectionTimeOut' => 30,
            'log.LogEnabled' => true,
            'log.FileName' => __DIR__.'/../PayPal.log',
            'log.LogLevel' => 'FINE'
        ));

    }

    /*
     * Create payment using credit card
     * url:payment/create
    */
    public function create(){

        // ### Address
        // Base Address object used as shipping or billing
        // address in a payment. [Optional]
        $addr= Paypalpayment::Address();
        $addr->setLine1("3909 Witmer Road");
        $addr->setLine2("Niagara Falls");
        $addr->setCity("Niagara Falls");
        $addr->setState("NY");
        $addr->setPostal_code("14305");
        $addr->setCountry_code("US");
        $addr->setPhone("716-298-1822");

        // ### CreditCard
        // A resource representing a credit card that can be
        // used to fund a payment.
        $card = Paypalpayment::CreditCard();
        $card->setType("visa");
        $card->setNumber("4417119669820331");
        $card->setExpire_month("11");
        $card->setExpire_year("2019");
        $card->setCvv2("012");
        $card->setFirst_name("Anouar");
        $card->setLast_name("Abdessalam");
        $card->setBilling_address($addr);

        // ### FundingInstrument
        // A resource representing a Payer's funding instrument.
        // Use a Payer ID (A unique identifier of the payer generated
        // and provided by the facilitator. This is required when
        // creating or using a tokenized funding instrument)
        // and the `CreditCardDetails`
        $fi = Paypalpayment::FundingInstrument();
        $fi->setCredit_card($card);


        // ### Payer
        // A resource representing a Payer that funds a payment
        // Use the List of `FundingInstrument` and the Payment Method
        // as 'credit_card'
        $payer = Paypalpayment::Payer();
        $payer->setPayment_method("credit_card");
        $payer->setFunding_instruments(array($fi));

        // ### Amount
        // Let's you specify a payment amount.
        $amount = Paypalpayment:: Amount();
        $amount->setCurrency("USD");
        $amount->setTotal("1.00");

        // ### Transaction
        // A transaction defines the contract of a
        // payment - what is the payment for and who
        // is fulfilling it. Transaction is created with
        // a `Payee` and `Amount` types
        $transaction = Paypalpayment:: Transaction();
        $transaction->setAmount($amount);
        $transaction->setDescription("This is the payment description.");

        // ### Payment
        // A Payment Resource; create one using
        // the above types and intent as 'sale'
        $payment = Paypalpayment:: Payment();
        $payment->setIntent("sale");
        $payment->setPayer($payer);
        $payment->setTransactions(array($transaction));

        // ### Create Payment
        // Create a payment by posting to the APIService
        // using a valid ApiContext
        // The return object contains the status;
        try {
            $payment->create($this->_apiContext);
        } catch (\PPConnectionException $ex) {
            return "Exception: " . $ex->getMessage() . PHP_EOL;
            var_dump($ex->getData());
            exit(1);
        }

        $response=$payment->toArray();

        echo"<pre>";
        print_r($response);

        //var_dump($payment->getId());

        //print_r($payment->toArray());//$payment->toJson();
    }  

    /*
        Use this call to get a list of payments. 
        url:payment/
    */
    public function index(){

        echo "<pre>";

        $payments = Paypalpayment::all(array('count' => 1, 'start_index' => 0),$this->_apiContext);

         print_r($payments);
    }
}

**Comment by chilion** [comment]
Ah allright, seems good. config/app.php, added facades and serviceprovider

**Comment by imdketav** [comment]
@chilion  in my config/app.php file there is not a service provider but providers is there and i already add this line to providers array 
Anouar\Paypalpayment\PaypalpaymentServiceProvider::class,

and in Aliases array
'Paypalpayment'   => Anouar\Paypalpayment\Facades\PaypalPayment::class,

But there is not a single work like facades..

Can you explain it to me?

**Comment by xroot** [comment]
@imdketav : try composer dumpautoload if it doest work , please watch the video https://www.youtube.com/watch?v=q5Xb5r4MUB8 you may missed something

**Comment by imdketav** [comment]
@xroot : I have been watched video given you and I found where is problem.
Problem is In **vendor** folder only anouar folder is there but  **paypalpayment folder is not available**.
That's why I am getting error **Class 'Anouar\Paypalpayment\Facades\PaypalPayment' not found**
![screenshot from 2015-10-09 11 03 05](https://cloud.githubusercontent.com/assets/15032918/10386466/5c336ef0-6e75-11e5-9ef0-bf506fdebc48.png)

**Comment by imdketav** [comment]
@xroot : Video given you that helps me a lot. But I'm still getting one error like this **Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/payment.**

How can I fix this error?
![screenshot from 2015-10-09 15 24 49](https://cloud.githubusercontent.com/assets/15032918/10391055/ee181f4a-6e99-11e5-9866-85a38d0e4a57.png)

**Comment by xroot** [comment]
@imdketav share with me your code , also make sure your paypal API keys are correct , for testing use sandbox api keys

**Comment by imdketav** [comment]
@xroot Following is my code
**Code of PaypalPaymentController.php**
    <?php

    namespace my_app\Http\Controllers;

    use Illuminate\Http\Request;
    use my_app\Http\Requests;
    use my_app\Http\Controllers\Controller;
    use Paypalpayment;

    class PaypalPaymentController extends Controller {
     /**
         * object to authenticate the call.
         * @param object $_apiContext
         */
        private $_apiContext;

        /**
         * Set the ClientId and the ClientSecret.
         * @param
         *string $_ClientId
         *string $_ClientSecret
         */
        private $_ClientId = 'xxxxxxxxxxx';
        private $_ClientSecret='xxxxxxxxxxxxx';

        /*
         *   These construct set the SDK configuration dynamiclly,
         *   If you want to pick your configuration from the sdk_config.ini file
         *   make sure to update you configuration there then grape the credentials using this code :
         *   $this->_cred= Paypalpayment::OAuthTokenCredential();
        */
        public function __construct()
        {

            // ### Api Context
            // Pass in a `ApiContext` object to authenticate
            // the call. You can also send a unique request id
            // (that ensures idempotency). The SDK generates
            // a request id if you do not pass one explicitly.

            $this->_apiContext = Paypalpayment::ApiContext(config('paypal_payment.Account.ClientId'), config('paypal_payment.Account.ClientSecret'));

            // Uncomment this step if you want to use per request
            // dynamic configuration instead of using sdk_config.ini

            $this->_apiContext->setConfig(array(
                'mode' => 'sandbox',
                'service.EndPoint' => 'https://api.sandbox.paypal.com',
                'http.ConnectionTimeOut' => 30,
                'log.LogEnabled' => true,
                'log.FileName' => __DIR__.'/../PayPal.log',
                'log.LogLevel' => 'FINE'
            ));
        }

         /*
            Use this call to get a list of payments. 
            url:payment/
        */
        public function index()
        {
            echo "<pre>";

            $payments = Paypalpayment::getAll(array('count' => 1, 'start_index' => 0), $this->_apiContext);

            dd($payments);
        }
     /*
        * Display form to process payment using credit card
        */
        public function create()
        {
            echo "Hello";die;
            return View::make('payment.order');
        }

        /*
        * Process payment using credit card
        */
        public function store()
        {
            // ### Address
            // Base Address object used as shipping or billing
            // address in a payment. [Optional]
            $addr= Paypalpayment::address();
            $addr->setLine1("3909 Witmer Road");
            $addr->setLine2("Niagara Falls");
            $addr->setCity("Niagara Falls");
            $addr->setState("NY");
            $addr->setPostalCode("14305");
            $addr->setCountryCode("US");
            $addr->setPhone("716-298-1822");

            // ### CreditCard
            $card = Paypalpayment::creditCard();
            $card->setType("visa")
                ->setNumber("4758411877817150")
                ->setExpireMonth("05")
                ->setExpireYear("2019")
                ->setCvv2("456")
                ->setFirstName("Joe")
                ->setLastName("Shopper");

            // ### FundingInstrument
            // A resource representing a Payer's funding instrument.
            // Use a Payer ID (A unique identifier of the payer generated
            // and provided by the facilitator. This is required when
            // creating or using a tokenized funding instrument)
            // and the `CreditCardDetails`
            $fi = Paypalpayment::fundingInstrument();
            $fi->setCreditCard($card);

            // ### Payer
            // A resource representing a Payer that funds a payment
            // Use the List of `FundingInstrument` and the Payment Method
            // as 'credit_card'
            $payer = Paypalpayment::payer();
            $payer->setPaymentMethod("credit_card")
                ->setFundingInstruments(array($fi));

            $item1 = Paypalpayment::item();
            $item1->setName('Ground Coffee 40 oz')
                    ->setDescription('Ground Coffee 40 oz')
                    ->setCurrency('USD')
                    ->setQuantity(1)
                    ->setTax(0.3)
                    ->setPrice(7.50);

            $item2 = Paypalpayment::item();
            $item2->setName('Granola bars')
                    ->setDescription('Granola Bars with Peanuts')
                    ->setCurrency('USD')
                    ->setQuantity(5)
                    ->setTax(0.2)
                    ->setPrice(2);


            $itemList = Paypalpayment::itemList();
            $itemList->setItems(array($item1,$item2));


            $details = Paypalpayment::details();
            $details->setShipping("1.2")
                    ->setTax("1.3")
                    //total of items prices
                    ->setSubtotal("17.5");

            //Payment Amount
            $amount = Paypalpayment::amount();
            $amount->setCurrency("USD")
                    // the total is $17.8 = (16 + 0.6) * 1 ( of quantity) + 1.2 ( of Shipping).
                    ->setTotal("20")
                    ->setDetails($details);

            // ### Transaction
            // A transaction defines the contract of a
            // payment - what is the payment for and who
            // is fulfilling it. Transaction is created with
            // a `Payee` and `Amount` types

            $transaction = Paypalpayment::transaction();
            $transaction->setAmount($amount)
                ->setItemList($itemList)
                ->setDescription("Payment description")
                ->setInvoiceNumber(uniqid());

            // ### Payment
            // A Payment Resource; create one using
            // the above types and intent as 'sale'

            $payment = Paypalpayment::payment();

            $payment->setIntent("sale")
                ->setPayer('$payer')
                ->setTransactions(array($transaction));

            try {
                // ### Create Payment
                // Create a payment by posting to the APIService
                // using a valid ApiContext
                // The return object contains the status;
                $payment->create($this->_apiContext);
            } catch (\PPConnectionException $ex) {
                return  "Exception: " . $ex->getMessage() . PHP_EOL;
                exit(1);
            }

            dd($payment);
        } 

            /*
            Use this call to get details about payments that have not completed, 
            such as payments that are created and approved, or if a payment has failed.
            url:payment/PAY-3B7201824D767003LKHZSVOA
        */

        public function show($payment_id)
        {
           $payment = Paypalpayment::getById($payment_id,$this->_apiContext);

           dd($payment);
        }

    }

**Routers.php**

Route::post('payment', 'PaypalPaymentController@create');

**config/app.php**

 'providers' => [
                       //My code
                       Anouar\Paypalpayment\PaypalpaymentServiceProvider::class,
                      //My code
  ],
 'aliases' => [
                   //My Code
                    'Paypalpayment'     => Anouar\Paypalpayment\Facades\PaypalPayment::class,
                    //My Code
 ],

Client ID and Client Secret Both are correct that i know.
This is a code which i did and i am getting following error while i'm trying to run it.
**with POST Method**
![selection_005](https://cloud.githubusercontent.com/assets/15032918/10446034/e42a8940-7197-11e5-8823-21e5e2195481.png)

**with GET Method**
![selection_006](https://cloud.githubusercontent.com/assets/15032918/10446096/2f6cad8e-7198-11e5-93d4-41f16ac4ff1a.png)

**Comment by xroot** [comment]
@imdketav : I have updated your code , check it now , from the error I may guess you're not using the correct API keys.

**Comment by imdketav** [comment]
@xroot I'm still getting same error..
when I use Client ID and Client Secret in Core PHP Paypal Integration then it works perfectly. Only in Laravel I'm facing problem.

**Comment by imdketav** [comment]
fvxcvxcvxcvxcvxv

**Comment by xroot** [comment]
@imdketav please watch this video https://www.youtube.com/watch?v=q5Xb5r4MUB8&feature=youtu.be

**Comment by karthikjs** [comment]
@anouarabdsslm 
 am getting 

PaymentHistory {#171
  -_propMap: []
}
what response am getting. how proceed next step.....

how to give a payment details via api as well as website. pls help
****

**Comment by prabhat2k15** [comment]
![error](https://cloud.githubusercontent.com/assets/26509407/24422268/8cc2acbe-1416-11e7-8369-8f6c41b621c2.png)
i am getin this error...how to get rid of this..
