### ISSUE TITLE
 Got Http response code 401 when accessing https://api.sandbox.paypal.com/v1/oauth2/token.

### ISSUE THREAD

**Issue by ChristianGB** [xroot/laravel-paypalpayment#31]
I got this when I send my request to paypal for payments  Got Http response code 401 when accessing https://api.sandbox.paypal.com/v1/oauth2/token.

**Comment by xroot** [comment]
does your issue resolved?

**Comment by ChristianGB** [comment]
Sorry for the latest reply.

Yes I fixed all problems and thank you for you interest

2015-01-13 8:39 GMT-06:00 Anouar Absslm <notifications@github.com>:

> does your issue resolved?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xroot/laravel-paypalpayment/issues/31#issuecomment-69753003>
> .
>



-- 

*Christian Eduardo Galdámez Blanco*

*Ingeniero en Desarrollo de Software*

*Facebook: https://www.facebook.com/shiroiMangetsu
<https://www.facebook.com/shiroiMangetsu>Teléfono: 044 961 270 47 69*

**Comment by xroot** [comment]
your welcome
