### ISSUE TITLE
Http response code 400 when list of items is added

### ISSUE THREAD

**Issue by fogine** [xroot/laravel-paypalpayment#33]
When I run this piece of code with paypal item list set, I get Error:  
`Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/payment.`

But if I comment out`$transaction->setItemList($itemList)`, I'm successfully redirected to paypal confirmation page.

What I'm doing wrong?

    public function someFunction()
    {
        $payer = PaypalPayment::payer();
        $payer->setPayment_method("paypal");        

        $amount = PaypalPayment::amount();
        $amount->setCurrency('USD')
                ->setTotal(20);

        $paypalItem = PaypalPayment::item();
        $paypalItem->setName('dasfasdl')
            ->setCurrency('USD')
            ->setQuantity(1)
            ->setPrice(20);

        $itemList = Paypalpayment::itemList();
        $itemList->setItems([$paypalItem]);

        $transaction = PaypalPayment::transaction();
        $transaction->setAmount($amount);
        $transaction->setItemList($itemList);  // This line cause the issue, Item list is array of one paypal item object
        $transaction->setDescription("Payment description");
        $transaction->setInvoiceNumber(545465);

        $baseUrl = Request::root();
        $redirectUrls = PaypalPayment::redirectUrls();
        $redirectUrls->setReturn_url($baseUrl.'/payment/confirmpayment');
        $redirectUrls->setCancel_url($baseUrl.'/payment/cancelpayment');

        $payment = PaypalPayment::payment();
        $payment->setIntent("sale");
        $payment->setPayer($payer);
        $payment->setRedirectUrls($redirectUrls);
        $payment->setTransactions([$transaction]);

        $response = $payment->create($this->apiContext);

        $this->paymentId = $response->id;

        $redirectUrl = $response->links[1]->href;

        return Redirect::to($redirectUrl);
    }

**Comment by fogine** [comment]
Problem was caused by diversity of `$amount->setTotal(20);` amount value and sum of all order item prices. The values must be exact same.

**Comment by xroot** [comment]
yes I have already mentioned this on the doc

**Comment by cedrico2016** [comment]
thank you very much for this ticket.. i've checking for this error for hours...
