### ISSUE TITLE
Is there any support for "Adaptive Simple Payments "?

### ISSUE THREAD

**Issue by teddywest32** [xroot/laravel-paypalpayment#34]
I just want to implement paypal in laravel for paying the people who request for payout. Is there any method so that i can use the feature of paypal?
Thanks in advance

**Comment by anistark** [comment]
+1 I too need it. Does this package support adaptive payments ? @xroot

**Comment by xroot** [comment]
Hi  guys sorry for the delay , currently we're using a  REST API which has no support for adaptive payments , I am not sure if paypal have added this functionality  with latest REST APIs versions.
