### ISSUE TITLE
Support Laravel 5.0.*

### ISSUE THREAD

**Issue by KalinKanev** [xroot/laravel-paypalpayment#35]
Please support Laravel 5.0.*

**Comment by xroot** [comment]
will go with that in the next future

**Comment by majimboo** [comment]
Is there a date for this?

**Comment by xroot** [comment]
Actually no but soon

**Comment by KadeorAgency** [comment]
We can't wait. Any estimations?

**Comment by xroot** [comment]
Upgraded , use ~1.* to get laravel 5 version 1.1 for laravel 4 . let me know if something goes wrong.
