### ISSUE TITLE
Error new parameter in Json 'TransactionFee'

### ISSUE THREAD

**Issue by dimension3000** [xroot/laravel-paypalpayment#36]
There is an error with this new parameter in json.

Method PayPal\Api\Sale::getTransactionFee() does not exist

Apparently the current classes are not contemplating this new response parameter.

**Comment by mb303** [comment]
It's due to the old version of the paypal api that is being used. I have created a fork and included the latest version of the API without any problems so far.

**Comment by xroot** [comment]
we're using version "0.15.1" of paypal API , and there is no getTransactionFee() method available with the Sale calass
