### ISSUE TITLE
Laravel 5 error

### ISSUE THREAD

**Issue by KadeorAgency** [xroot/laravel-paypalpayment#37]
There is an error when i try to get any url:

BadMethodCallException in ServiceProvider.php line 226:
Call to undefined method [package]

I only installed project according to instruction.

**Comment by LoveAndHappiness** [comment]
Is this package even intended to work for Laravel 5?

**Comment by KadeorAgency** [comment]
According to this issue - YES, it is.
https://github.com/xroot/laravel-paypalpayment/issues/35

**Comment by damienIN** [comment]
I resolved this by deleting $this->package() in the service provider. It appears Laravel 5 no longer requires this in package definitions.

**Comment by damienIN** [comment]
I was able to get this working in L5 with minor tweaks to the ServiceProvider, I can fork and submit a pull request if you want to see what I did.

**Comment by xroot** [comment]
create your pull request also make sure when you run the test it is passed
.thanks

**Comment by xroot** [comment]
Fixed
