### ISSUE TITLE
Laravel 4.2 error when Paypal redirect PatmentSuccess page.

### ISSUE THREAD

**Issue by vandung2k6** [xroot/laravel-paypalpayment#38]
HI all, please help me.

I am using Laravel 4.* 

in file composer
...
 "anouar/paypalpayment": "1.0"
...

Made payment success on Paypal but when redirect to Pay Success page (my website)

Error: Call to undefined method Anouar\Paypalpayment\PaypalPayment::get()

My code succes page:

// Get the payment Object by passing paymentId
        // payment id and payer ID was previously stored in database in
        // create() fuction , this function create payment using "paypal" method
        $paymentId = $_GET['paymentId'];
        $PayerID = $_GET['PayerID'];
        $payment = Paypalpayment::get($paymentId, $this->_apiContext);

        // PaymentExecution object includes information necessary 
        // to execute a PayPal account payment. 
        // The payer_id is added to the request query parameters
        // when the user is redirected from paypal back to your site
        $execution = Paypalpayment::PaymentExecution();
        $execution->setPayerId($PayerID);

        //Execute the payment
        $payment->execute($execution,$this->_apiContext);

Please help me.
Thanks so much.

**Comment by xroot** [comment]
check this issue https://github.com/xroot/laravel-paypalpayment/issues/14 seems the same
