### ISSUE TITLE
Please Upgrade the PayPal SDK to fix an error in 1.0 release

### ISSUE THREAD

**Issue by josephilipraja** [xroot/laravel-paypalpayment#40]
Am getting an error - 
```
exception 'ReflectionException' with message 'Method PayPal\Api\Sale::getTransactionFee() does not exist' 
in /opt/lampp/htdocs/************/vendor/paypal/rest-api-sdk-php/lib/PayPal/Common/PPReflectionUtil.php:73
```
When I digged in Google found that it was some weird compatibility error from PayPal SDK itself.
(Refer: https://github.com/paypal/PayPal-PHP-SDK#latest-updates). 
In their page they said:
>Seeing this error: 'Method PayPal\Api\Sale::getTransactionFee() does not exist' in paypal/vendor/paypal/rest-api-sdk-php/lib/PayPal/Common/PPReflectionUtil.php:73, Please upgrade the SDK to latest version v1.3.0.

So please update *your ``` 1.0 ``` release* to the latest PayPal SDK (```1.3.0```) version to fix this error! Currently it seems to use a very old ```0.15.1```.

Awaiting your fix!!

**Comment by xroot** [comment]
Done , go ahead and try it now , sorry for the delay
