### ISSUE TITLE
Composer 

### ISSUE THREAD

**Issue by nemo3000** [xroot/laravel-paypalpayment#43]
I'm using L5 and with command anouar/paypalpayment:~1.* I have an error and if I use 1.* I have old version not for L5, to solv problem I have overwrite folder from the online version.

**Comment by xroot** [comment]
try anouar/paypalpayment:1.*

**Comment by xroot** [comment]
if that doesn't work follow thus steps:
* -Remove the package entirely from under vendor folder
* -Remove the package from composer.json file
*- under composer.lock file find the package object and remove it , do the same for the paypal sdk , we're using new one .
* - Run: composer require anouar/paypalpayment:1.* --prefer-source
Now you should have the L5 version .
Feel free to reopen this issue if it doesn't work
