### ISSUE TITLE
Use Laravel Config

### ISSUE THREAD

**Issue by gravitano** [xroot/laravel-paypalpayment#46]
Hi,

I know we can merge the config directly from the controller. But, would be nice if we can update the config via Laravel config instead of `ini` file. My suggestion is added a config file that can be publish to the `config` folder, maybe.

**Comment by xroot** [comment]
ok do that and create

**Comment by chriskonnertz** [comment]
The whole config is managed by the official PayPal library (paypal/rest-api-sdk-php) so one cannot simlply replace the ini file with a Laravel config file. You had to override parts of the official PayPal library. Honestly - forget about it.

The best thing to do is to copy the ini file to your app directory, e. g. to `app/config/packages/paypal` and to define a constant with the name `PP_CONFIG_PATH` and set it to the new path of the file, e.g: `define('PP_CONFIG_PATH', 'app/config/packages/paypal');`

**Comment by xroot** [comment]
Hi guys, it's really  simple to add a configuration file, you don't need to use ini file , you can use the  build in setConfiguration function like so ```$apiContext->setConfig(['your configuration])``` , check the readme for more details. I'll update the readme file to include a guide how to use config file soon .if you can create pull request for thats will be great :)

**Comment by chriskonnertz** [comment]
For what exactly?

**Comment by xroot** [comment]
add config file to the package

**Comment by chriskonnertz** [comment]
Done: https://github.com/xroot/laravel-paypalpayment/pull/48

Changelog:
- Updated Readme a little bit
- Created a config file in Laravel style
- Updated the service provider so one can publish the config with the `artisan vendor:publish` command.

It's not actually **using** the new config file!!!

**Comment by xroot** [comment]
when you run the artisan publish command , do you get the file published ?

**Comment by chriskonnertz** [comment]
Yes.

**Comment by xroot** [comment]
I did not try it yet .I'm going to merge it

**Comment by chriskonnertz** [comment]
Okay, great. Here is how to use it:

```
    $apiContext = Paypalpayment::ApiContext(..., ...);
    
    $config     = config('paypal_payment'); // Get all config items as multi dimensional array
    $flatConfig = array_dot($config); // Flatten the array with dots
    
    $apiContext->setConfig($flatConfig);
```

**Comment by xroot** [comment]
Add this to the readme file and create new pull request :)

**Comment by xroot** [comment]
I'm going to close this issue guys , feel free to reopen it if you need anymore details.
