### ISSUE TITLE
Examples in readme.md

### ISSUE THREAD

**Issue by Yorkii** [xroot/laravel-paypalpayment#50]
Examples in readme.md won't work since methods are not longer static.

**Comment by xroot** [comment]
please watch this https://www.youtube.com/watch?v=q5Xb5r4MUB8

**Comment by Yorkii** [comment]
Yeah, I know how to implement it with latest laravel, but other programmers may be confused by following steps in readme.md :) However, great module :)

**Comment by xroot** [comment]
For laravel 4 use this branch instead https://github.com/xroot/laravel-paypalpayment/tree/l4 . thanks
