### ISSUE TITLE
Error: Method PayPal\Api\Sale::getTransactionFee() does not exist

### ISSUE THREAD

**Issue by josephilipraja** [xroot/laravel-paypalpayment#52]
Am getting this error while a successful payment is made on Sandbox/Live
`` Method PayPal\Api\Sale::getTransactionFee() does not exist ``

While digging in google found that it was a PayPal API SDK bug, which was fixed on a newer release of the SDK. Could you please update the PayPal SDK version of this project? That might fix this issue.

Ref: https://github.com/paypal/PayPal-PHP-SDK/issues/255

**Comment by Geekathon** [comment]
+1 , Please update the SDK.

**Comment by josephilipraja** [comment]
Hello @xroot please advice a way out of this..

**Comment by xroot** [comment]
Hi guys,
Could you please create pull request , if not give me some time ,I'm bit
busy :(

**Comment by pelhage** [comment]
So does the SDK needs to be updated? I've been running into multiple issues: 400 error, and Method PayPal\Api\Sale::getFmfDetails() does not exist.

**Comment by xroot** [comment]
please watch the video to make to sure you have implemented the package correctly https://www.youtube.com/watch?v=q5Xb5r4MUB8
