### ISSUE TITLE
SetExpressCheckout - question

### ISSUE THREAD

**Issue by adrianoGaspar** [xroot/laravel-paypalpayment#53]
Hi, please help me.
It's possible work with SetExpressCheckout? How
Tankyou

**Comment by wessodesigner** [comment]
Want to know that too. How can we use paypal express instead of credit cards payments?

**Comment by xroot** [comment]
if you want to use payment without credit card , just switch setPaymentMethod to paypal instead of credit_card . I'll create a demo video within this week about this ....
