### ISSUE TITLE
Add multiple items

### ISSUE THREAD

**Issue by yulioDamian** [xroot/laravel-paypalpayment#59]
I'm trying to add several products in a settlement but sends me an error
Is this

public function addItem($items){
        $item=Paypalpayment::item();
        $item->setName($item->name)
             >setDescription($items>descripcion)
             ->setCurrency('USD')
             >setQuantity($items>cantidad)
             ->setTax(0.2)
             >setPrice($items>precio);
         return $item;    
    }

$prod=Producto::all();
        $productos=array();
        //$productos [];
        $total = Producto::sum('precio');
        foreach ($prod as $p) {
            array_push($productos,$this->addItem($p));

        }

el error
PayPalConnectionException in PayPalHttpConnection.php line 176: Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/payment.

**Comment by pelhage** [comment]
From what I've gathered, it looks like this SDK is outdated. (Someone correct me if I'm wrong)

**Comment by yulioDamian** [comment]
Already solved the problem
Items=array()
Foreach(producto as key=>p)
Items[key]=item
